name: CI - Validación del Proyecto

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Si tienes un archivo de requerimientos, descomenta la siguiente línea:
          pip install -r app/requirements.txt

      - name: Ejecutar pruebas (Antes paso CodeBuild)
        run: python -m pytest tests/

      - name: Finalización
        run: echo "Validación finalizada con éxito"
